-- Retrieve each film category's name and the total revenue (i.e. total payment amount) generated by all films within that category.
-- Only include categories where the total revenue exceeds 10k
-- Sort the results by total revenue in `descending` order.

-- Hint: You will need to join category, film_category, film, inventory, rental and payment tables

SELECT 
    category.name,
    SUM(payment.amount) AS total_revenue
FROM category
INNER JOIN film_category ON film_category.category_id = category.category_id
INNER JOIN film ON film.film_id = film_category.film_id
INNER JOIN inventory ON inventory.film_id = film.film_id
INNER JOIN rental ON rental.inventory_id = inventory.inventory_id
INNER JOIN payment ON payment.rental_id = rental.rental_id
GROUP BY category.name
HAVING SUM(payment.amount) > 10000
ORDER BY total_revenue DESC;
