-- Retrieve total revenue generated by each store in the database
-- Result should include store id, total revenue of each store,
-- Revenue should be calculated based on payments made by customers
-- Sort results based on total revenue in descending order

SELECT
    store.store_id, SUM(payment.amount) AS total_revenue
FROM store
JOIN customer ON customer.store_id = store.store_id
JOIN payment ON payment.customer_id = customer.customer_id
GROUP BY store.store_id
ORDER BY total_revenue DESC;

