-- Medium Difficulty
-- Topic: Aggregations and Multi-Table Joins
-- Anaylzing Revenue for each Payment Method
-- # Determine the total revenue generated by each payment method used by customers
-- # Result must present `payment method name` and `total amount collected via each method`.
-- # Sort results by total revenue in descending order, showing the highest-grossing payment method first

